# Generated by Django 5.2.6 on 2025-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertpreference',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
