# Generated by Django 5.0.7 on 2025-09-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='entire_organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='teams',
            field=models.ManyToManyField(blank=True, to='users.team'),
        ),
        migrations.AddField(
            model_name='alert',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.user'),
        ),
    ]
